"""create constraint CASCADE user_id for likes

Revision ID: e8eaf0a2143f
Revises: eeab4d57e638
Create Date: 2026-07-28 22:22:51.312073

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8eaf0a2143f'
down_revision: str | Sequence[str] | None = 'eeab4d57e638'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('likes_review_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_review_id_fkey'), 'likes', 'reviews', ['review_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
