"""add created_at in carts

Revision ID: 733f50b0aa0c
Revises: 37cf01953197
Create Date: 2026-07-06 20:52:32.704723

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "733f50b0aa0c"
down_revision: str | Sequence[str] | None = "37cf01953197"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carts",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("carts", "created_at")
    # ### end Alembic commands ###
