"""add revoked and created_at in sessions

Revision ID: dc81e1549bdb
Revises: d0b798bb2a87
Create Date: 2026-06-27 21:57:42.903672

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc81e1549bdb"
down_revision: str | Sequence[str] | None = "d0b798bb2a87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("revoked", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("sessions", "revoked")
    # ### end Alembic commands ###
