"""deleted phone_number to users

Revision ID: 75b0cc67b0c3
Revises: 4d371dc6897f
Create Date: 2026-06-30 23:17:39.445476

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75b0cc67b0c3"
down_revision: str | Sequence[str] | None = "4d371dc6897f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_number_phone_key"), "users", type_="unique")
    op.drop_column("users", "number_phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "number_phone", sa.VARCHAR(length=15), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint(
        op.f("users_number_phone_key"),
        "users",
        ["number_phone"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
