"""editing a refresh token to a string data type

Revision ID: 989ec376a0dd
Revises: 2f527cd8b293
Create Date: 2026-06-18 21:09:51.548619

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "989ec376a0dd"
down_revision: str | Sequence[str] | None = "2f527cd8b293"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("refresh_token", sa.String(), nullable=False))
    op.drop_constraint(op.f("sessions_refresh_jti_key"), "sessions", type_="unique")
    op.create_unique_constraint(None, "sessions", ["refresh_token"])
    op.drop_column("sessions", "refresh_jti")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column("refresh_jti", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "sessions", type_="unique")
    op.create_unique_constraint(
        op.f("sessions_refresh_jti_key"),
        "sessions",
        ["refresh_jti"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("sessions", "refresh_token")
    # ### end Alembic commands ###
