"""add total_price in carts_items

Revision ID: c406604acbf8
Revises: 42a8828d065c
Create Date: 2026-07-07 22:44:34.352068

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c406604acbf8"
down_revision: str | Sequence[str] | None = "42a8828d065c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carts_items",
        sa.Column(
            "total_price",
            sa.Numeric(precision=10, scale=2),
            sa.Computed(
                "quantity * price_at_add",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("carts_items", "total_price")
    # ### end Alembic commands ###
