"""editing a auth_ssid from sessions to a string data type

Revision ID: d8d00ab9e64c
Revises: 989ec376a0dd
Create Date: 2026-06-19 13:19:06.150461

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8d00ab9e64c"
down_revision: str | Sequence[str] | None = "989ec376a0dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "auth_ssid",
        existing_type=sa.UUID(),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "auth_ssid",
        existing_type=sa.String(length=64),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
