"""edit the auth_public_uuid column to auth_public_uid in sessions

Revision ID: d0b798bb2a87
Revises: d9005202f4b5
Create Date: 2026-06-24 22:35:43.660352

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0b798bb2a87"
down_revision: str | Sequence[str] | None = "d9005202f4b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("auth_public_uid", sa.String(length=64), nullable=False)
    )
    op.drop_constraint(
        op.f("sessions_auth_public_uuid_key"), "sessions", type_="unique"
    )
    op.create_unique_constraint(None, "sessions", ["auth_public_uid"])
    op.drop_column("sessions", "auth_public_uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "auth_public_uuid",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "sessions", type_="unique")
    op.create_unique_constraint(
        op.f("sessions_auth_public_uuid_key"),
        "sessions",
        ["auth_public_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("sessions", "auth_public_uid")
    # ### end Alembic commands ###
