"""add column is_blocked: bool = False and add table blacklists

Revision ID: 64bf186a9afa
Revises: 604203048989
Create Date: 2026-07-04 20:40:45.989676

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64bf186a9afa"
down_revision: str | Sequence[str] | None = "604203048989"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklists",
        sa.Column("reason", sa.String(length=50), nullable=True),
        sa.Column("ban_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_blocked", sa.Boolean(), nullable=False))
    op.drop_column("users", "active_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("active_at", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "is_blocked")
    op.drop_column("users", "is_active")
    op.drop_table("blacklists")
    # ### end Alembic commands ###
