"""edit constraint parent_id ondelete=set null from categories, also edit constraint category_id onupdate=cascade

Revision ID: d0058b26e2d0
Revises: 5a09fdb010bc
Create Date: 2026-07-04 22:44:44.897725

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0058b26e2d0"
down_revision: str | Sequence[str] | None = "5a09fdb010bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "sku",
        existing_type=sa.Uuid(),
        postgresql_using="sku::text",
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "sku",
        existing_type=sa.VARCHAR(),
        postgresql_using="sku::uuid",
        type_=sa.Uuid(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
