"""add constraint a nullable=True in password for users

Revision ID: ad0fc1b20df0
Revises: bf2e8f717b36
Create Date: 2026-06-20 13:08:21.962689

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad0fc1b20df0"
down_revision: str | Sequence[str] | None = "bf2e8f717b36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=25), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=25), nullable=False
    )
    # ### end Alembic commands ###
