"""edit parant_id: nullable=True from categories

Revision ID: 5a09fdb010bc
Revises: 70f79760af45
Create Date: 2026-07-04 22:03:18.048914

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a09fdb010bc"
down_revision: str | Sequence[str] | None = "70f79760af45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories", "parent_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories", "parent_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
