"""edit data type for column expires_at = datatime(tz=true)

Revision ID: 1baafd9e7859
Revises: 56b4a8f83fad
Create Date: 2026-06-22 17:26:12.803542

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1baafd9e7859"
down_revision: str | Sequence[str] | None = "56b4a8f83fad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("auth_public_uuid", sa.String(length=64), nullable=False)
    )
    op.alter_column(
        "sessions",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("sessions_auth_public_uid_key"), "sessions", type_="unique")
    op.create_unique_constraint(None, "sessions", ["auth_public_uuid"])
    op.drop_column("sessions", "auth_public_uid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "auth_public_uid",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "sessions", type_="unique")
    op.create_unique_constraint(
        op.f("sessions_auth_public_uid_key"),
        "sessions",
        ["auth_public_uid"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "sessions",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("sessions", "auth_public_uuid")
    # ### end Alembic commands ###
