"""add constraint unique_product_id_user_id

Revision ID: 9abe54e12781
Revises: a59c1ae1afba
Create Date: 2026-08-18 20:09:42.869986

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9abe54e12781'
down_revision: str | Sequence[str] | None = 'a59c1ae1afba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_product_id_user_id_for_reviews', 'reviews', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_product_id_user_id', 'reviews', type_='unique')
    # ### end Alembic commands ###
