"""edit sku: UUID from products

Revision ID: 70f79760af45
Revises: 3ef9005c7bc3
Create Date: 2026-07-04 21:55:35.904343

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70f79760af45"
down_revision: str | Sequence[str] | None = "3ef9005c7bc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "sku",
        existing_type=sa.VARCHAR(),
        postgresql_using="sku::uuid",
        type_=sa.Uuid(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "sku",
        existing_type=sa.Uuid(),
        postgresql_using="sku::text",
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
