"""edit sku: str from products

Revision ID: a7df3dc8576a
Revises: d0058b26e2d0
Create Date: 2026-07-05 00:03:00.232129

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7df3dc8576a"
down_revision: str | Sequence[str] | None = "d0058b26e2d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "sku",
        existing_type=sa.UUID(),
        postgresql_using="sku::text",
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "sku",
        existing_type=sa.String(),
        postgresql_using="sku::uuid",
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
