"""add table likes

Revision ID: e44724c87e7c
Revises: 4ce31e701699
Create Date: 2026-07-17 12:57:31.927216

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e44724c87e7c"
down_revision: str | Sequence[str] | None = "4ce31e701699"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], onupdate="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "review_id", name="unique_review_id_user_id"),
    )
    op.create_index(
        "idx_user_review_id", "likes", ["user_id", "review_id"], unique=False
    )
    op.drop_constraint(op.f("reviews_user_id_fkey"), "reviews", type_="foreignkey")
    op.create_foreign_key(
        None, "reviews", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key(
        op.f("reviews_user_id_fkey"), "reviews", "users", ["user_id"], ["id"]
    )
    op.drop_index("idx_user_review_id", table_name="likes")
    op.drop_table("likes")
    # ### end Alembic commands ###
