"""add an updated primary key to sessions as an integer id

Revision ID: c27e57b8000c
Revises: d8d00ab9e64c
Create Date: 2026-06-19 14:29:58.800680

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c27e57b8000c"
down_revision: str | Sequence[str] | None = "d8d00ab9e64c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auth_ssid", sa.String(length=64), nullable=False),
        sa.Column("refresh_token", sa.String(length=64), nullable=False),
        sa.Column("auth_public_uid", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=False),
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_public_uid"),
        sa.UniqueConstraint("auth_ssid"),
        sa.UniqueConstraint("refresh_token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    # ### end Alembic commands ###
