"""add active_at:bool in users

Revision ID: bf2e8f717b36
Revises: c27e57b8000c
Create Date: 2026-06-19 16:46:57.395780

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf2e8f717b36"
down_revision: str | Sequence[str] | None = "c27e57b8000c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("active_at", sa.Boolean(), default=True, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active_at")
    # ### end Alembic commands ###
