"""add column updated: boolean

Revision ID: 1a5cfbec9309
Revises: a402670bee69
Create Date: 2026-06-29 19:49:11.649416

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a5cfbec9309"
down_revision: str | Sequence[str] | None = "a402670bee69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("update", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "update")
    # ### end Alembic commands ###
