"""edit status: String(25) in orders

Revision ID: 4db956ede1da
Revises: 2067cb3ecab6
Create Date: 2026-07-10 22:15:29.815529

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4db956ede1da"
down_revision: str | Sequence[str] | None = "2067cb3ecab6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.BOOLEAN(),
        type_=sa.String(length=25),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.String(length=25),
        type_=sa.BOOLEAN(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
