"""add surname: str | None in users

Revision ID: 4d371dc6897f
Revises: 48205a6a37cc
Create Date: 2026-06-30 12:31:21.105166

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d371dc6897f"
down_revision: str | Sequence[str] | None = "48205a6a37cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("surname", sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "surname")
    # ### end Alembic commands ###
