"""add constraint in reviews review_rating and in products product_rating, product_review_count

Revision ID: 6eae19723d75
Revises: ae7163a16154
Create Date: 2026-07-13 15:47:44.344784

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6eae19723d75"
down_revision: str | Sequence[str] | None = "ae7163a16154"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "product_rating",  # Имя ограничения
        "products",  # Имя таблицы в БД (из __tablename__)
        "rating >= 0 AND rating <= 5",  # SQL-условие
    )
    op.create_check_constraint("product_review_count", "products", "review_count >= 0")

    op.create_check_constraint(
        "review_rating",
        "reviews",
        "rating >= 0 AND rating <= 5",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "product_rating",  # Имя ограничения
        "products",  # Имя таблицы в БД (из __tablename__)
        "check",  # SQL-условие
    )
    op.drop_constraint("product_review_count", "products", "check")

    op.drop_constraint(
        "review_rating",
        "reviews",
        "check",
    )
    # ### end Alembic commands ###
