"""add parent_id in roles

Revision ID: 98f769f75394
Revises: 6dc6ac8335ae
Create Date: 2026-07-21 14:20:15.122737

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98f769f75394"
down_revision: str | Sequence[str] | None = "6dc6ac8335ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "roles", "roles", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_column("roles", "parent_id")
    # ### end Alembic commands ###
