"""edit column password: String(150) from users

Revision ID: 604203048989
Revises: 75b0cc67b0c3
Create Date: 2026-07-02 23:28:42.994182

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "604203048989"
down_revision: str | Sequence[str] | None = "75b0cc67b0c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.String(length=150),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=25),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
