"""add rating in the products

Revision ID: 098b2a14922f
Revises: b8bd5beb8b2e
Create Date: 2026-07-05 20:26:40.813309

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "098b2a14922f"
down_revision: str | Sequence[str] | None = "b8bd5beb8b2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("rating", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "rating")
    # ### end Alembic commands ###
