"""delete column "user_id" from roles

Revision ID: 56b4a8f83fad
Revises: ad0fc1b20df0
Create Date: 2026-06-21 22:08:05.894374

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56b4a8f83fad"
down_revision: str | Sequence[str] | None = "ad0fc1b20df0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("roles_user_id_fkey"), "roles", type_="foreignkey")
    op.drop_column("roles", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("roles_user_id_fkey"),
        "roles",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
